Drop database if exists iba;

create database iba;

use iba;

create table if not exists user(
user_id varchar(40) unique,
email varchar(40) not null,
password varchar(60) not null,
erstelltam timestamp,
primary key (user_id)
);

create table if not exists praeferenzen(
user_id varchar(40),
Genre varchar(30) not null,
Plattform varchar(30) not null,
zeit int(30) not null,
FSK int(30) not  null,
Player varchar(30) not null,
Budget int(30) not null,
primary key (user_id)
);

create table if not exists Spiele(
spiel_id int unique auto_increment,
spieletitel varchar(100),
cover varchar(600) ,
genre varchar(100),
plattform varchar(100),
zeit_aufwand int(100),
alterbeschraenkung int(100),
single_multiplayer varchar(100),
budget int(100),
beschreibung text(69420),
PRIMARY KEY (spiel_id)
);

/*Insert statement für Spiele*/
INSERT INTO Spiele (spieletitel, cover, genre, plattform, zeit_aufwand, alterbeschraenkung, single_multiplayer, budget, beschreibung)
VALUES ("The Witcher 3: Wild Hunt", "/WhatToPlay/Bilder_WhatToPlay/Witcher3WildHunt.jpg", "Rollenspiel", "PC, XBOX ONE, PS4, Nintendo Switch", "50", "18", "Singleplayer", "40", "In diesem Spiel basierend auf einer Bücherreihe, steht in der Hauptrolle Der Hexer Geralt von Riva. Dieser ist auf der Suche nach seiner Ziehtochter Ciri, sie flieht vor der „Wilden Jagd“, in einer Welt gefüllt von Monstern und Problemen. Dabei muss sich Geralt dem alltäglichen Rassismus stellen."),
("XCOM: Enemy Unknown", "/WhatToPlay/Bilder_WhatToPlay/XCOMEnemyUnknown.jpg", "Strategie", "PC", "30", "16", "Singleplayer, Multiplayer", "30", "Übernimm als Kommandant einer Spezialeinheit die Führung gegen Aliens in diesem glorreichen rundenbasierten Strategiespiel. Dabei musst du dich nicht nur in spannenden Kämpfen beweisen, sondern auch die Basis verwalten und dabei schwierige Entscheidungen treffen. Währenddessen kann die Welt auch in Panik verfallen, sofern man nicht die richtigen Entscheidungen trifft…"),
("Crash Bandicoot N. Sane Trilogy", "/WhatToPlay/Bilder_WhatToPlay/CrashBandicootMNSane.jpg", "Jump & Run", "PC, XBOX ONE, PS4, Nintendo Switch", "15", "6", "Singleplayer", "40", "Die Trilogie, neu aufgemacht! Erlebe alle drei Klassiker in wunderschöner Grafik und flüssigem Gameplay. Springe durch viele verschiedene Level, quer durch die Spiele hindurch und erlebe die Nostalgie."),
("BioShock Remastered", "/WhatToPlay/Bilder_WhatToPlay/BioShock.jpg", "Shooter", "PC, XBOX ONE, PS4", "12", "18", "Singleplayer", "20", "Ein Shooter Klassiker neu aufgelegt! Erlebe die dunkle und düstere Atmosphäre der untergegangenen Stadt Rapture, damals ein Paradies für die gehobene Schicht, heute eine versunkene Stadt, in der einige Gefahren lauern. Lerne dabei die Little Sisters und die Big Daddys kennen und erfahre, was mit Rapture passiert ist."),
("Spyro Reignited Trilogy", "/WhatToPlay/Bilder_WhatToPlay/SpyroReignited.jpg", "Jump & Run", "PC, XBOX ONE, PS4, Nintendo Switch", "16", "6", "Singleplayer", "40", "Sei Spyro, der ikonische lila Drache, der in Drei Spielen seine Verwandenten retten muss. Springe dabei durch verschiedene Level, spucke Feuer und fliege! Dabei gibt es auch viel zu sammeln und zu entdecken, sodass das Sammlerherz höherschlägt."),
("Yooka-Laylee", "/WhatToPlay/Bilder_WhatToPlay/YookaLaylee.png", "Jump & Run", "PC, Nintendo Switch", "15", "6", "Singleplayer, Multiplayer", "40", "Ein Jump & Run mit viel Sammelgegenständen. Schlüpfe in die Rolle von Yooka, der grünen Eidechse und erkunde mithilfe von Laylee, der lilanen Fledermaus, die verschiedenen Welten. Dabei erwarten dich einige Bosskämpfe und Verbesserungen, die das Spielprinzip noch weiter ergänzen."),
("BattleBlock Theater", "/WhatToPlay/Bilder_WhatToPlay/BattleBlockTheater.jpg", "Jump & Run", "PC", "10", "12", "Singleplayer, Multiplayer", "15", "Ein Jump & Run mit verrücktem Humor. Du bist ein gestrandeter und landest in einem verlassenen Theater. Du musst deinen allerbesten Freund, Hatty Hattington, vor den bösen Katzen retten. Springe dabei von Level zu Level, erhalte neue Fähigkeiten und sammle Grüne Edelsteine. Mit einem Freund wird es noch viel besser, da das gesamte Spiel im Co-op spielbar ist, nur muss man dabei aufpassen, sich gegenseitig nicht zu sehr zu ärgern."),
("Final Fantasy X/X-2HD Remaster", "/WhatToPlay/Bilder_WhatToPlay/FinalFantasyXHDRemaster.jpeg", "Rollenspiel", "PC, XBOX ONE, PS4, Nintendo Switch", "55", "12", "Singleplayer", "30", "Die fantastische Geschichte von Final Fantasy X und X-2 in neuer Grafik und ein paar kleineren Änderungen. Erlebe die Geschichte von Tidus, einem Blitzballspieler, der kurzerhand aus seiner Realität gezogen wird. Er findet sich im Kontinent Spira wieder, wo er nun Yuna kennlernt, ein Medium, welches das uralte Böse „Sin“ aufhalten muss. Innerhalb dieser wichtigen Reise wird die Geschichte sehr verzwickt und dramatisch und irgendwann zweifelt man an der bloßen Existenz. Gespielt wird dabei in rundenbasierten Kämpfen, rüste deine Charaktere aus, verbessere Ihre Fähigkeiten und rette Spira vor dem Untergang. <br> Final Fantasy X-2 spielt viele Jahre nach den Ereignissen von X. Dabei steht Yuna diesmal im Fokus und wie sie mit den Ereignissen aus dem ersten Teil umgeht. Dabei ist es eher Echtzeit und nicht mehr strategisch so tief wie Final Fantasy X."),
("Super Smash Bros. Ultimate", "/WhatToPlay/Bilder_WhatToPlay/SmashBros.png", "Action", "Nintendo Switch", "22", "12", "Singleplayer, Multiplayer", "55", "In Smash kann man sich selbst aussuchen wie man Spielen will weil es viele Arten gibt zu Spielen, man kann mit seinen Freunden ganz Casual mit Items spielen oder auch Try-harden und ohne Items sondern nur auf Skill basierend Spielen. Aufgrund der hohen anzahl der Charaktere und der Stages gibt es Unzählige Möglichkeiten wie man dieses Spiel spielen will."),
("A Hat in Time", "/WhatToPlay/Bilder_WhatToPlay/AHatInTime.jpg", "Jump & Run", "PC, XBOX ONE, PS4, Nintendo Switch", "9", " 12", "Singleplayer, Multiplayer", "30", "Ein 3D Jump & Run indem man durch verschiedene Welten Reist um die Timepieces die HatKid der Hauptcharakter dieses Spiels durch ein Missgeschick verloren hat wieder zurück zu holen. Auf dem weg macht man sich viele Freunde und die Welte sind ziemlich offen und bieten hinter fast jeder Ecke verbirgt sich eine Überraschung."),
("GTA V", "/WhatToPlay/Bilder_WhatToPlay/GTA5.jpg", "Action", "PC, XBOX ONE, PS4", "30", "18", "Singleplayer, teilweise Multiplayer", "30", "Man spielt insgesamt 3 Charaktere die mehrere Raubüberfälle zusammen machen, aber alles in allen bietet GTA einen riesigen Spielplatz indem man sehr viel Spaß haben kann, zum Beispiel man versucht sich einen Panzer aus Merryweather zu stehlen oder versuchen solange wie möglich gegen die Polizei anzukommen. Aber der Hauptaspekt des Spieles ist der Online Modus weil man mit seinen Freunden Rennen fahren oder auch große Überfälle machen kann."),
("Overwatch", "/WhatToPlay/Bilder_WhatToPlay/Overwatch.jpg", "Shooter", "PC, XBOX ONE, PS4, Nintendo Switch", "42", "16", "Multiplayer", "20", "In diesem Team Shooter wird Team Groß geschrieben, denn wenn man nicht auf seine Team Kollegen achtet, bekommt man ein Problem und das Gegnerische Team wird Unbesiegbar wenn diese Zusammen arbeiten. Denn in Overwatch gibt es drei Verschiedene Arten von Helden, die Tanks, die Angreifer und die Heiler. Am meisten macht Overwatch allerdings mit Freunden Spaß da man sich dann während des Kampfes absprechen kann."),
("South Park der Stab der Wahrheit", "/WhatToPlay/Bilder_WhatToPlay/SouthPark.jpg", "Rollenspiel", "PC, XBOX ONE, PS4, Nintendo Switch", "12", "16", "Singleplayer", "30", "Wer die Serie kennt und mag wird dieses Spiel auch mögen denn es ist derselbe Humor und Story ist genauso Verrückt. Man spielt nämlich den neuen der in die Stadt gezogen ist und befindet sich in einem Spiel das sich die anderen Kinder ausgedacht haben welches sich im Fantasy Mittelalter befindet."),
("South Park die Rektakuläre Zerreißprobe", "/WhatToPlay/Bilder_WhatToPlay/SouthPark2.jpg", "Rollenspiel", "PC, XBOX ONE, PS4, Nintendo Switch", "17", "16", "Singleplayer", "50", "Wie der erste Teil ist dieser genauso Verrückt nur das man in diesem teil nicht im Fantasy Mittelalter befindet sondern dieses mal ein Superheld ist der auf der suche nach einer Katze ist und versucht mit dem Finderlohn ein Franchise aufzubauen."),
("Super Mario Odyssey", "/WhatToPlay/Bilder_WhatToPlay/SuperMarioOdyssey.jpg", "Jump & Run", "Nintendo Switch", "13", "6", "Singleplayer, Multiplayer", "60", "In diesem Spiel ist Mario nicht mehr alleine Unterwegs sondern bekommt einen neuen Freund und Kameraden, und zwar Cappy der von nun an seine neue Mütze ist und mit dem er von nun an gegner Übernehmen kann und somit neue Fähigkeiten erhält. Der Plot ist allerdings wieder das man wieder versucht Peach von Bowser rettet und dafür durch insgesamt 14 Königreiche reist."),
("SteamWorld Heist", "/WhatToPlay/Bilder_WhatToPlay/SteamWorldHeist.jpg", "Strategie", "PC, PS4, Nintendo Switch", "12", "12", "Singleplayer", "15", "In diesem rundenbasierten Strategiespiel schlüpfst du in die Rolle eines Roboters. Du bist Teil des Widerstands gegen das Imperium. Dabei musst du in einem X-COM ähnlichen Spielprinzip in 2D gegnerische Roboter aufhalten. Verwalte deine Crew, Level sie auf, rüste sie aus, kaufe neue Ausrüstung und erfahre, was wirklich hinter dem Universum steckt."),
("Bastion", "/WhatToPlay/Bilder_WhatToPlay/Bastion.png", "Action", "PC, PS4", "6", "12", "Singleplayer", "15", "Aufgewacht als ahnungsloser Junge. Die Welt wurde durch eine Katastrophe zerstört und nur ein alter Mann steht dir bei, der dein gesamtes Abenteuer nacherzählt, dabei ist seine Erzählerstimme definitiv ein Pluspunkt. Im Laufe des Abenteuers triffst du auf ein paar andere Leute, um die sich auch dramatische Geschichten entwickeln. Am Ende des Spiels steht eine schwerwiegende Entscheidung bevor und keiner kann dir bei der Entscheidung helfen. Gespielt wird in einer Top-Down Perspektive, spiele mit verschiedenen Waffen, verbessere sie und überlebe gegen viele fiese Gegner."),
("Counter Strike: Global Offensive", "/WhatToPlay/Bilder_WhatToPlay/CSGO.jpg", "Shooter", "PC", "42", "18", "Multiplayer", "0", "Ein zeitloser Multiplayer Shooter. Spiele in vielen verschiedenen Modi gegeneinander. Sei es Waffenrennen oder klassisches Deathmatch oder auch Bombenabwehr. Dabei macht jeder Modus spaß auf seiner eigenen weiße. Auch im Ranked kann man sich beweisen, obwohl dass schon eine Herausforderung sein kann. An die Waffen und los!"),
("Metin 2", "/WhatToPlay/Bilder_WhatToPlay/Metin2.jpg", "Rollenspiel", "PC", "42", "12", "Multiplayer", "0", "Stelle dich düsteren Kreaturen und kämpfe dich durch gefährliche Dungeons! Dein Abenteuer beginnt. Kampfkunst-Master gesucht. Kämpf für den Drachengott. Rasante Fantasy-Action. Schärfe Klinge und Geist. Kostenlose Fantasy-Action."),
("The Binding of Isaac: Rebirth", "/WhatToPlay/Bilder_WhatToPlay/IsaacRebirth.jpg", "Action, Adventure", "PC, XBOX ONE, PS4, Nintendo Switch", "5", "16", "Singleplayer, teilweise Mutliplayer", "15", "Ein Rogue-like welches seinesgleichen sucht. Jeder Versuch im Spiel unterscheidet sich deutlich vom letzten, sei darauf vorbereitet zu sterben. Dabei fühlt es sich aber nie unfair an, man macht stetigen Fortschritt und wird immer besser, bis man dann schließlich jeden Versuch erfolgreich meistert. Aber hinter jeder Ecke lauert ein Raum mit einer neuen Überraschung…"),
("Fire Emblem: Three Houses", "/WhatToPlay/Bilder_WhatToPlay/FireEmblemThreeHouses.jpg", "Strategie, Rollenspiel", "Nintendo Switch", "50", "12", "Singleplayer", "60", "Ein weiterer Ableger der weit gefeierten rundenbasierten Strategiereihe, diesmal auf der Switch. Es gibt Drei verschiedene Pfade zu wählen und unterteilt wird zwischen einer Rollenspielphase und einer rundenbasierten Strategiephase. Dabei steckt unglaublich viel Detail im Spiel, da jeder Entscheidung das Spiel beeinflusst. Ein würdiger Nachfolger für diese lange Reihe."),
("Darkest Dungeon", "/WhatToPlay/Bilder_WhatToPlay/DarkestDungeon.png", "Strategie, Rollenspiel", "PC, XBOX ONE, PS4, Nintendo Switch", "50", "12", "Singleplayer", "25", "Ein sehr düsteres Abenteuer im wunderschönen Stil. Sei darauf vorbereitet zu verzweifeln, denn dieses Spiel nimmt keine Gefangenen, es ist aber auch nicht Unfair. Sollte etwas schiefgehen, so ist es immer deine Schuld. Dabei bewegt man sich in Dungeons in Echtzeit, sobald man auf Gegner trifft wechselt das Ganze in Runden. Helden können sterben, aber auch gestresst werden, dabei gibt es ein Perma-Death System. Aber nicht nur das, auch das Hamlet, die Stadt, muss verwaltet werden und dabei gilt es die begrenzten Ressourcen richtig zu verwenden. Du wirst sterben, und es wird dir gefallen."),
("Fallout 4", "/WhatToPlay/Bilder_WhatToPlay/Fallout4.jpg", "Shooter, Rollenspiel", "PC, XBOX ONE, PS4", "27", "18", "Singleplayer", "30", "Der Open-World Shooter mit einem post-apokalyptischen Setting. Entdecke die grenzenlosen Weiten, lerne die Welt und seine Bürger kennen und finde deinen Sohn!"),
("Batman Arkham Knight", "/WhatToPlay/Bilder_WhatToPlay/BatmanArkhamKnight.jpg", "Adventure, Rollenspiel", "PC, XBOX ONE, PS4", "16", "16", "Singleplayer", "15", "Der letzte Teil der Batman Arkham Reihe. Schlüpfe dabei in die Rolle von Batman, dem Rächer der Nacht und halte den verschlagenen Arkham Knight auf bei seinen diabolischen Plänen! Erkunde dabei mithilfe des Bat Mobils Arkham City und mache in der Zwischenzeit einige andere Bösewichte Dingfest wie den Riddler."),
("Dark Souls 3", "/WhatToPlay/Bilder_WhatToPlay/DarkSouls3.jpg", "Rollenspiel, Action", "PC, XBOX ONE, PS4", "33", "16", "Singleplayer, Multiplayer", "60", "Der Dritte Ableger der Souls Reihe. Erlebe epische Bosskämpfe, haarsträubende Kämpfe und sei darauf vorbereitet, zu sterben, denn das wird oft passieren. Das Ganze kann mit Freunden gespielt werden, damit man zusammen verzweifeln kann. Rüste deinen Charakter individuell aus, sei es mit Großschwert oder Dolch. Doch sei gewarnt, selbst das Tutorial haben nur 80% der Spieler überhaupt geschafft.."),
("Monster Hunter World", "/WhatToPlay/Bilder_WhatToPlay/MonsterHunterWorld.jpg", "Action, Rollenspiel", "PC, XBOX ONE, PS4", "50", "12", "Singleplayer, Multiplayer", "60", "Jäger, bist du bereit die neue Welt zu erkunden? Jage epische Kreaturen, verbessere deine Ausrüstung, stelle neue her. Jage mit bis zu 4 Spielern ein Monster! Sammle immer mehr Ressourcen und stelle dir die beste Ausrüstung her, denn die wirst du brauchen! Bezwinge Drachenälteste und erkunde die Mysteriösen Ereignisse in der neuen Welt."),
("The Legend of Zelda Breath of the Wild", "/WhatToPlay/Bilder_WhatToPlay/ZeldaBOTW.jpg", "Adventure, Rollenspiel", "Nintendo Switch", "50", "12", "Singleplayer", "55", "In diesem Spiel kann man ansich machen was man will denn es gibt dir einen großen Baukasten wie die verschiedenen Module die die Hauptitems aus den alten Spielen ersetzen und der Offenen Story denn man wird direkt ins Spiel geworfen und muss sich erstmal Zurecht finden, alles ist eine Entdeckung und wenn man ganz Mutig ist kann man direkt zum Endboss und versuchen ihn zu Besiegen."),
("Pokemon Schild und Schwert", "/WhatToPlay/Bilder_WhatToPlay/PokemonSchwertSchild.jpg", "Rollenspiel, Adventure", "Nintendo Switch", "30", "6", "Singleplayer, teilweise Multiplayer", "60", "Es ist das neuste Spiel der Pokemon Reihe und findet in der Galar-Region statt. In diesem Teil wird das bekannte Schema etwas durchbrochen. Man besucht zwar immer noch Arenen und gewinnt die Orden allerdings tritt man am Ende nicht mehr gegen die Top Vier an sondern nimmt an einem Turnier teil und der Gewinner darf dann gegen den Champ Kämpfen."),
("Sekiro Shadows Die Twice", "/WhatToPlay/Bilder_WhatToPlay/Sekiro.jpg", "Action, Adventure", "PC, XBOX ONE, PS4", "30", "18", "Singleplayer", "60", "In diesem dynamischen Abenteuer bist du in der Rolle eines Samurais, der sich gegen massenhaft Gegner beweisen muss. Dabei wird es vorkommen, dass du stirbst, aber nur Mut! Kontere deine Gegner und erkunde die Asiatische Fantasiewelt."),
("For the King", "/WhatToPlay/Bilder_WhatToPlay/FitForAKing.jpg", "Strategie, Rollenspiel", "PC, XBOX ONE, PS4, Nintendo Switch", "12", "12", "Singleplayer, Multiplayer", "20", "Es fühlt sich wie ein Pen and Paper an. Am Anfang sucht man sich eine Questreihe aus von denen es mehrere gibt, entweder man macht Für den König oder ein Tiefsee Abenteuer oder man begibt sich auf ein Abenteuer im Schnee. Obwohl es momentan wenige Abenteuer gibt, hat das Spiel genug zu bieten denn meistens schafft man die Abenteuer im ersten Anlauf gar nicht und versucht es dann darum immer wieder.");





